return {
  {
    "nvim-treesitter/nvim-treesitter",
    version = "*",
    lazy = false,

    dependencies = {
      "nvim-tree/nvim-web-devicons",
    },

    opts = {
      ensure_installed = {
        "angular",
        "arduino",
        "bash",
        "c",
        "c_sharp",
        "clojure",
        "cmake",
        "comment",
        "cpp",
        "css",
        "csv",
        "cuda",
        "dart",
        "diff",
        "dockerfile",
        "fish",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "goctl",
        "gomod",
        "gosum",
        "gotmpl",
        "gowork",
        "haskell",
        "hcl",
        "helm",
        "html",
        "htmldjango",
        "http",
        "java",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "julia",
        "just",
        "kotlin",
        "latex",
        "lua",
        "luadoc",
        "luap",
        "markdown",
        "markdown_inline",
        "nginx",
        "php",
        "phpdoc",
        "powershell",
        "pymanifest",
        "python",
        "r",
        "regex",
        "ruby",
        "rust",
        "sql",
        "ssh_config",
        "swift",
        "tmux",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "wgsl",
        "xml",
        "yaml",
      },

      sync_install = false,
      auto_install = true,

      highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
      },
    },
  },
  {
    "nvim-treesitter/nvim-treesitter-context",
    after = "nvim-treesitter",
  },
}
